language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - rust: nightly
      env: TOOLCHAIN=nightly
  allow_failures:
    - rust: nightly
cache: cargo

before_script:
  - rustup component add clippy rustfmt

script:
  - cargo fmt --all -- --check
  - RUST_TEST_THREADS=1 cargo test -p beeline-rust -p beeline-actix-web -- --nocapture # We have to set RUST_TEST_THREADS=1 due to a limitation in the mockito library
  - ([ "$TOOLCHAIN" = "nightly" ] && RUST_TEST_THREADS=1 cargo test -p beeline-rocket -- --nocapture) || exit 0
  - cargo clippy -p beeline-rust -p beeline-actix-web --all-targets --all-features -- -D clippy::nursery
  - ([ "$TOOLCHAIN" = "nightly" ] && cargo clippy -p beeline-rocket --all-targets --all-features -- -D clippy::nursery) || exit 0
