language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - rust: nightly
      env: TOOLCHAIN=nightly
  allow_failures:
    - rust: nightly
cache: cargo

before_script:
  - rustup component add clippy rustfmt

script:
  - cargo fmt --all -- --check
  - cargo test -p beeline-rust -p beeline-actix-web -- --nocapture
  - ([ "$TOOLCHAIN" = "nightly" ] && cargo test -p beeline-rocket -- --nocapture) || exit 0
  - cargo clippy -p beeline-rust -p beeline-actix-web --all-targets --all-features -- -D clippy::nursery
  - ([ "$TOOLCHAIN" = "nightly" ] && cargo clippy -p beeline-rocket --all-targets --all-features -- -D clippy::nursery) || exit 0
